name: Tahoma2D Linux Build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        compiler: [ clang ]
        include:
          - compiler: clang
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: bash ./ci-scripts/linux/tahoma-install.sh
      - name: Build ffmpeg
        run: bash ./ci-scripts/linux/tahoma-buildffmpeg.sh
      - name: Build OpenCV
        run: bash ./ci-scripts/linux/tahoma-buildopencv.sh
      - name: Build Tahoma2D
        run: bash ./ci-scripts/linux/tahoma-build.sh
      - name: Create Package
        run: bash ./ci-scripts/linux/tahoma-buildpkg.sh
      - uses: actions/upload-artifact@v1
        with:
          name: Tahoma2D-linux.tar.gz
          path: toonz/build/Tahoma2D-linux.tar.gz
