name: Tahoma2D macOS Build

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          ci-scripts/osx/tahoma-install.sh
          brew install ccache
          mkdir /Users/runner/.ccache
      - uses: actions/cache@v2
        with:
          path: |
            /Users/runner/.ccache
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/aom
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/ffmpeg
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/ffmpeg_shared
            /Users/runner/work/tahoma2d/taoma2d/thirdparty/opencv
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      - name: Build ffmpeg
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-buildffmpeg.sh
      - name: Build OpenCV
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-buildopencv.sh
      - name: Build Tahoma2D
        run: |
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          ci-scripts/osx/tahoma-build.sh
      - name: Get 3rd Party Apps
        run: |
          ci-scripts/osx/tahoma-get3rdpartyapps.sh
      - name: Create Package
        run: bash ./ci-scripts/osx/tahoma-buildpkg.sh
      - uses: actions/upload-artifact@v1
        with:
          name: Tahoma2D-osx.dmg
          path: toonz/build/Tahoma2D-osx.dmg
